#!/usr/bin/env python3
import sys
from tfnz.location import Location
from tfnz.components.mail.mail import Mail

if len(sys.argv) != 5:
    print("Usage: mail_server location fqdn volume user:password")
    exit(1)

loc = Location(sys.argv[1], debug_log=True)
m = Mail(sys.argv[2], [sys.argv[4]])
m.go(loc, sys.argv[3], log_callback=lambda c, s: print(s.decode(), end=''))
