.TH TF(1)
.SH NAME
tf - launch a container on 20ft.nz
.SH SYNOPSIS
.B tf
[\fB\-h\fR]
[\fB\-v\fR]
[\fB\-\-loc \fIxxx.20ft.nz\fR]
[\fB\-\-local_broker \fIyyy.local\fR]
[\fB\-\-bind \fIaa.bb.cc.dd\fIn\fR]
[\fB\-\-latest\fR]
[\fB\-\-json \fIfilename\fR]
[\fB\-\-browser\fR
[\fB\-\-domain \fIhost.name\fR]
[\fB\-\-path \fI/where/ever\fR]]
\fB\fIimage\fR
[\fB\fIENVIRONMENT=\fIvalue \fR[\fB\fIENVIRONMENT=VALUE \fR...]]
.SH DESCRIPTION
.B tf
Launches containers on 20ft.nz, passes the environment variables and creates localhost tunnels to ports 'exposed' within the Docker config. Use \fB\-\-loc\fR to specify a non-default location and \fB\-\-local_broker\fR to specify a connection ip other than that obtained by a dns lookup.

Find localhost addresses using the \fB\-\-json\fR file or directly attach a browser with \fB\-\-browser\fR with an optional hostname sent as the HTTP Host header. Note that for the browser to attach the hostname needs to resolve to 127.0.0.1 - tf will help you do this if necessary..

Using . as the image name launches this machine's most recently built docker image.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Present cli help.
.TP
.BR \-v
Increase verbosity (up to 2)
.TP
.BR \-\-loc\ xxx\.20ft\.nz
Use an (optional) non-default location (fqdn)
.TP
.BR \-\-local_broker\ yyy.local
An optional (local) ip for the broker
.TP
.BR \-\-bind\ aa.bb.cc.dd
Binds to an address other than localhost
.TP
.BR \-\-json\ filename
Writes a file describing state (deleted on exit)
.TP
.BR \-\-browser\ host.name
Create web browser onto container port 80
.TP
.BR \-\-domain\ some.domain
Pass to replace 'localhost' in the http server-name directive
.TP
.BR \-\-path\ /where/ever
The initial path to request from the webserver.
.SH EXIT CODES
tf will also write a verbose explanation to stderr:
.TP
.BR 3
Environment variables malformed
.TP
.BR 4
An attempt has been made to instantiate two instances referencing the same json file
.TP
.BR 5
There was a failure while connecting to the location
.TP
.BR 6
There was a failure selecting a node
.TP
.BR 7
There was a failure while spawning a container
.TP
.BR 8
Attempted to use a domain that does not resolve to localhost
.TP
.BR 9
There was a failure while writing the json file (permissions?)
.TP
.BR 9
Provided offset was not an integer
.SH EXAMPLES
Launch the most recently built Docker image and attach a browser.
.PP
.nf
.RS
tf --browser www.example.host .
.RE
.fi
.PP
Launch nginx container with an environment variable set.
.PP
.nf
.RS
tf nginx DOMAIN=test.org
.RE
.fi
.PP
Create from local ID dcff15633c66, report state as json file.
.PP
.nf
.RS
tf --local_ip broker.local --json js_filename dcff15633c66
.RE
.fi
